config/routes.rb
Rails.application.routes.draw do
  resources :schedules
  get 'welcome/index'
  resources :welcome
  resources :profiles
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "welcome#index"

  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image_uploader.rb
class ImageUploader < Shrine
    
end

app/models/profile.rb
class Profile < ApplicationRecord
  include ImageUploader::Attachment.new(:image)

  belongs_to :user
  
  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  after_commit :wakeup
  after_create :wakeup
  belongs_to :user
  
  def wakeup
    Scheduler.wake_up
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_one :profile
  has_many :schedules

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)
    @profile.user = current_user
    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :image)
    end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  # GET /schedules
  # GET /schedules.json
  def index
    @schedules = Schedule.all
    
    
    
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
    @schedule.user_id = current_user.id
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)

    respond_to do |format|
      if @schedule.save
        #Scheduler.wake_up
        format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        #Scheduler.wake_up
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule.destroy
    #Scheduler.wake_up
    respond_to do |format|
      format.html { redirect_to schedules_url, notice: 'Schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schedule_params
      params.require(:schedule).permit(:user_id, :run_at, :priority, :message, :next_month, :next_week, :next_day, :next_minutes, :valid_days, :start_time, :end_time)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    #ReminderMessageJob.set(wait_until: 5.minute).perform_later("test message for user 1", current_user.id)
    #ReminderMessageJob.perform_later("test message for user 1", current_user.id)
    ActionCable.server.broadcast "room_channel#{current_user.id}",
                                 message: 'Test message from controller'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CaHackathonToolsdown</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :profile_first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :profile_last_name %>
  </div>


  <div class="field">
    <%= form.label :image %>  
    <%= form.file_field :image, id: :profile_image %> <!--this is to enable upload of the image-->
  </div>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>


<div>
      <div class="btn btn-light">
        <%= link_to 'New Profile', new_profile_path %>
      </div>

        <% if user_signed_in? %>
            <div class="btn btn-light">
              <%= link_to "Edit Account", edit_user_registration_path %>
            </div>
            <div class="btn btn-light">
              <%= link_to "Sign Out", destroy_user_session_path, method: :delete%>
            </div>
            <% else %>
            <div class="btn btn-light">
              <%= link_to "Sign In", new_user_session_path %>
            </div>
            <div class="btn btn-light">
              <%= link_to "Sign Up", new_user_registration_path %>
            </div>
        <%end>%>
</div>

<hr>

<div class="container container-table">
  <div class="row vertical-center-row">
    <div class="text-center col-md-12 col-md-offset-12">

<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Photo</th>
      <th>First name</th>
      <th>Last name</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody> 
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= image_tag profile.image_url, size: "100x100" %>
        <td><%= profile.first_name %></td>
        <td><%= profile.last_name %></td>
        <td><%= profile.user.email %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<hr>

<div class="btn btn-light">
    <%= link_to 'Back', profiles_path %>
</div>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @profile.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @profile.last_name %>
</p>

<p>
   <%= image_tag @profile.image_url, size: "200x200" %>
</p>


<%= link_to 'Welcome', welcome_index_path %>
<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>

app/views/schedules/_form.html.erb
<%= form_with(model: schedule, local: true) do |form| %>
  <% if schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
      <% schedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :user_id, id: :schedule_user_id %>

  <div class="field">
    <%= form.label :run_at %>
    <%= form.datetime_select :run_at, id: :schedule_run_at %>
  </div>

  <div class="field">
    <%= form.label :priority %>
    <%= form.number_field :priority, id: :schedule_priority %>
  </div>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_field :message, id: :schedule_message %>
  </div>

  <div class="field">
    <%= form.label :next_month %>
    <%= form.number_field :next_month, id: :schedule_next_month %>
  </div>

  <div class="field">
    <%= form.label :next_week %>
    <%= form.number_field :next_week, id: :schedule_next_week %>
  </div>

  <div class="field">
    <%= form.label :next_day %>
    <%= form.number_field :next_day, id: :schedule_next_day %>
  </div>

  <div class="field">
    <%= form.label :next_minutes %>
    <%= form.number_field :next_minutes, id: :schedule_next_minutes %>
  </div>

  <div class="field">
    <%= form.label :valid_days %>
    <%= form.text_field :valid_days, id: :schedule_valid_days %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.time_select :start_time, id: :schedule_start_time %>
  </div>

  <div class="field">
    <%= form.label :end_time %>
    <%= form.time_select :end_time, id: :schedule_end_time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/schedules/edit.html.erb
<h1>Editing Schedule</h1>

<%= render 'form', schedule: @schedule %>

<%= link_to 'Show', @schedule %> |
<%= link_to 'Back', schedules_path %>

app/views/schedules/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Schedules</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Run at</th>
      <th>Priority</th>
      <th>Message</th>
      <th>Next month</th>
      <th>Next week</th>
      <th>Next day</th>
      <th>Next minutes</th>
      <th>Valid days</th>
      <th>Start time</th>
      <th>End time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schedules.each do |schedule| %>
      <tr>
        <td><%= schedule.user.profile.full_name %></td>
        <td><%= schedule.run_at %></td>
        <td><%= schedule.priority %></td>
        <td><%= schedule.message %></td>
        <td><%= schedule.next_month %></td>
        <td><%= schedule.next_week %></td>
        <td><%= schedule.next_day %></td>
        <td><%= schedule.next_minutes %></td>
        <td><%= schedule.valid_days %></td>
        <td><%= schedule.start_time %></td>
        <td><%= schedule.end_time %></td>
        <td><%= link_to 'Show', schedule %></td>
        <td><%= link_to 'Edit', edit_schedule_path(schedule) %></td>
        <td><%= link_to 'Destroy', schedule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Schedule', new_schedule_path %>

app/views/schedules/new.html.erb
<h1>New Schedule</h1>

<%= render 'form', schedule: @schedule %>

<%= link_to 'Back', schedules_path %>

app/views/schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @schedule.profile.full_name %>
</p>

<p>
  <strong>Run at:</strong>
  <%= @schedule.run_at %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @schedule.priority %>
</p>

<p>
  <strong>Message:</strong>
  <%= @schedule.message %>
</p>

<p>
  <strong>Next month:</strong>
  <%= @schedule.next_month %>
</p>

<p>
  <strong>Next week:</strong>
  <%= @schedule.next_week %>
</p>

<p>
  <strong>Next day:</strong>
  <%= @schedule.next_day %>
</p>

<p>
  <strong>Next minutes:</strong>
  <%= @schedule.next_minutes %>
</p>

<p>
  <strong>Valid days:</strong>
  <%= @schedule.valid_days %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @schedule.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @schedule.end_time %>
</p>

<%= link_to 'Edit', edit_schedule_path(@schedule) %> |
<%= link_to 'Back', schedules_path %>

app/views/welcome/_message.html.erb
<div id="message-block"><%= message %></div>

app/views/welcome/index.html.erb
<div class="container container-table">
  <div class="row vertical-center-row">
    <div class="text-center col-md-12 col-md-offset-12">
     <h1>Welcome</h1>
    </div>
  </div>
</div>
<div class="row vertical-center-row">
  <div class="text-center col-md-offset-12">
    <div id="message-block"></div>
  </div>
</div>

app/views/welcome/show.html.erb
<div class="container container-table">
  <div class="row vertical-center-row">
    <div class="text-center col-md-12 col-md-offset-12">
    <%= image_tag("tools_down.jpg", :alt => "Tools down logo", size: "500x200") %>
     <div>
      <br>
      <br>
      <h1>Welcome</h1>
     </div>
    </div>
  </div>
  <% if @display %>
  <div class="row vertical-center-row">
    <div class="text-center col-md-12 col-md-offset-12">
     <%= @message %>
  

    
    </div>
    <%end%>
  </div>
</div>